rules:
  - id: javascript-shell-command-injection-from-environment
    metadata:
      category: security
      cwe:
        - "CWE-78: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')"
      owasp:
        - "A01:2017 - Injection"
        - "A03:2021 - Injection"
        - "A05:2025 - Injection"
    languages:
      - javascript
      - typescript
    severity: ERROR
    message: Environment-controlled path reaches a shell command
    mode: taint

    pattern-sources:
      - pattern: path.join(__dirname, ...)

    pattern-sinks:
      - pattern-either:
          - pattern: $CP.execSync('rm -rf ' + path.join(__dirname, ...), ...)
          - pattern: $EXECA.shell('rm -rf ' + path.join(__dirname, ...), ...)
          - pattern: $EXECA.shellSync('rm -rf ' + path.join(__dirname, ...), ...)
